language: node_js
node_js:
- '6'
deploy:
  - provider: script
    script: ./travis-dist-deploy.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ./travis-dist-deploy.sh
    skip_cleanup: true
    on:
      branch: ci-publish
  - provider: script
    script: ./travis-dist-deploy.sh
    skip_cleanup: true
    on:
      tags: true
sudo: false
cache:
  directories:
  - node_modules
